setgano/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('steg/', include('steg.urls',namespace='steg')),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

steg/urls.py
from . import views
from django.urls import path
from django.conf.urls import include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

app_name = 'steg'
urlpatterns = [
    # path('upload', views.index_encode, name='upload'),
    path('', views.index, name='index'),

    path('show-image/<int:id>/', views.show_image, name='show_img'),
    path('show-image-decode/<int:id>/', views.show_image_decode, name='show_img_decode'),

    path('decode', views.index_decode, name='decode'),
    path('encode', views.encode, name='encode'),
    # path('lsbDecode', views.lsbDecode, name='lsbDecode'),
    path('lsb-encoder', views.lsb_encode, name='lsb-encoder'),
    path('addition-encoder', views.addition_encode, name='addition-encoder'),


]

steg/models.py
from django.db import models

# Create your models here.


class LSBEncode(models.Model):
    id = models.AutoField(primary_key=True)
    inputImagePath = models.FileField(
        upload_to='images/', null=False, verbose_name="")
    outputImagePath = models.FileField(
        upload_to='images/', null=True, verbose_name="")

    def __str__(self):
        return str(self.inputImagePath) + " ID : " + str(self.id)
    
    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('steg:show_img', kwargs={'id': self.id})


class LSBDecode(models.Model):
    id = models.AutoField(primary_key=True)
    inputImagePath = models.FileField(
        upload_to='images/', null=True, verbose_name="")
    message = models.TextField(max_length=1000, default="")

    def __str__(self):
        return str(self.inputImagePath)

    def get_absolute_url(self):
        from django.urls import reverse
        return reverse('steg:show_img_decode', kwargs={'id': self.id})

steg/forms.py
from django import forms

from steg.models import LSBEncode, LSBDecode


class ImageFormEncode(forms.ModelForm):
    message = forms.CharField(label='Secret Message', max_length=1000)
    # CHOICES = [('LSB', 'LSB'),
    #            ('Addition', 'Addition')]


    # algorithm = forms.ChoiceField(label="Which algorithm do you want to choose?", choices=CHOICES, widget=forms.RadioSelect)
    class Meta:
        model = LSBEncode
        fields = ["inputImagePath"]
        

class ImageFormDecode(forms.ModelForm):
    CHOICES = [('LSB', 'LSB'),
               ('Addition', 'Addition')]

    algorithm = forms.ChoiceField(label="Which algorithm do you want to choose?", choices=CHOICES, widget=forms.RadioSelect)

    class Meta:
        model = LSBDecode
        fields = ["inputImagePath"]

steg/views.py
from django.urls import reverse
from django.shortcuts import redirect, render

# Create your views here.

from django.http import HttpResponse

from numpy import imag

# from sympy import re
from .models import LSBEncode, LSBDecode
from .forms import ImageFormEncode, ImageFormDecode
from algo.lsb import lsb_encode_algo, lsb_decode_algo
from django.template.response import TemplateResponse


def index(request):
    return render(request, 'steg/index.html')


def lsb_encode(request):

    form = ImageFormEncode(request.POST or None, request.FILES or None)
    if form.is_valid():
        lsb_encode_model = form.save(commit=True)
        image_path = lsb_encode_model.inputImagePath
        image_id = lsb_encode_model.id
        # lsb_encode_model.algorithm = form.cleaned_data['algorithm']
        lsb_encode_model.message = form.cleaned_data['message']
        image_path = "media/"+str(image_path)
        # if lsb_encode_model.algorithm == 'LSB':
        output_path = lsb_encode_algo(str(image_path), lsb_encode_model.message)
        lsb_encode_model.outputImagePath = output_path[6:]
        lsb_encode_model.save()
        return redirect(lsb_encode_model)

    context = {
        'form': form
    }

    return render(request, 'steg/lsbEncoder.html', context)


def index_decode(request):

    form = ImageFormDecode(request.POST or None, request.FILES or None)
    if form.is_valid():
        lsb_decode_model = form.save(commit=True)
        image_path = lsb_decode_model.inputImagePath
        image_id = lsb_decode_model.id
        # lsb_decode_model.algorithm = form.cleaned_data['algorithm']
        image_path = "media/"+str(image_path)
        # print(image_id, image_path)
        # if lsb_decode_model.algorithm == 'LSB':
        message = lsb_decode_algo(str(image_path))

        # else:
        #     message = mnf_decode_algo(
        #         str(image_path))
        # args={}
        # args['key'] = message
        lsb_decode_model.message=message
        lsb_decode_model.save()
        image_path = lsb_decode_model.inputImagePath
        image_id = lsb_decode_model.id
        return redirect(lsb_decode_model)

    context = {
        'form': form
    }

    return render(request, 'steg/decode.html',context)


def show_image(request, id):
    image = LSBEncode.objects.filter(id=id).first()
    if image:
        return render(request, 'steg/show_image.html', {
            'image': image
        })
    pass


def show_image_decode(request, id):
    image = LSBDecode.objects.filter(id=id).first()
    if image:
        return render(request, 'steg/show_image_decode.html', {
            'image': image
        })
    pass

def decode(request):
    return render(request, 'steg/decode.html')


def encode(request):
    return render(request, 'steg/encode.html')

def addition_encode(request):
    return render(request, 'steg/additionEncoder.html')

# def lsbEncode(request):
#     return render(request, 'steg/lsbEncode.html')


# def lsbDecode(request):
#     return render(request, 'steg/decode.html')

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    
</body>
</html>

templates/steg/decode.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Decoder</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'steg/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/templatemo-style.css' %}">
</head>
<body style="background-color: rgb(210, 204, 187);  color: #000;">
    <section>
        <nav class="navbar navbar-expand-md tm-navbar" id="tmNav"
            style=" background-color: rgb(216, 161, 132);color: #000; margin-top: -10%;">
            <div class="container">
                <div class="tm-next">
                    <a href="{% url 'steg:index' %}" class="navbar-brand" style="color: #000;" title="Go to Home Page!">SETGANO</a>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="fas fa-bars navbar-toggler-icon"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="{% url 'steg:encode' %}"
                                style="color: #000;">ENCODE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="{% url 'steg:decode' %}"
                                style="color: #000;">DECODE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="#contact" style="color: #000;">CONTACT US</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>
    <div style="margin: 10%; z-index: -1;">
        <h1>SETGANO DECODER</h1>
        <br><br>
        <h2>Welcome! Choose an image of your choice to be decoded!</h2><br>
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Upload" class="tm-btn-primary"/>
        </form>
    
    
    </div>

    <section id="contact" style="margin: -5%; margin-top: 0;" class="tm-section-pad-top tm-parallax-2">
        <div class="container tm-container-contact">
            <div class="row">
                <div class="col-12">
                    <h2 class="mb-4 tm-section-title">Contact Us</h2>
                    <div class="mb-5 tm-underline">
                        <div class="tm-underline-inner"></div>
                    </div>
                    <p class="mb-5">
                        This is a project done by Poorna Hegde, Saniya Bhargava and Sonali R under Nirmal V Nair and
                        Ganesh
                        S for ACM NITK.
                    </p>
                </div>
    
                <div class="col-sm-12 col-md-6 d-flex align-items-center tm-contact-item">
                    <a href="tel:0100200340" class="tm-contact-item-link">
                        <span class="mb-0">0100200340</span>
                    </a>
                </div>
                <div class="col-sm-12 col-md-6 d-flex align-items-center tm-contact-item">
                    <a href="mailto:acm@nitk.edu.in" class="tm-contact-item-link">
                        <span class="mb-0">acm@nitk.edu.in</span>
                    </a>
                </div>
            </div>
        </div>
        <footer class="text-center small tm-footer">
            <p class="mb-0">
                Copyright &copy; 2022 ACM
    
                - Design: <a rel="nofollow" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
            </p>
        </footer>
    </section>
    <script src="js/jquery-1.9.1.min.js"></script>
    <script src="slick/slick.min.js"></script>
    <script src="magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.singlePageNav.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>

        function getOffSet() {
            var _offset = 450;
            var windowHeight = window.innerHeight;

            if (windowHeight > 500) {
                _offset = 400;
            }
            if (windowHeight > 680) {
                _offset = 300
            }
            if (windowHeight > 830) {
                _offset = 210;
            }

            return _offset;
        }

        function setParallaxPosition($doc, multiplier, $object) {
            var offset = getOffSet();
            var from_top = $doc.scrollTop(),
                bg_css = 'center ' + (multiplier * from_top - offset) + 'px';
            $object.css({ "background-position": bg_css });
        }

        // Parallax function
        // Adapted based on https://codepen.io/roborich/pen/wpAsm        
        var background_image_parallax = function ($object, multiplier, forceSet) {
            multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
            multiplier = 1 - multiplier;
            var $doc = $(document);
            // $object.css({"background-attatchment" : "fixed"});

            if (forceSet) {
                setParallaxPosition($doc, multiplier, $object);
            } else {
                $(window).scroll(function () {
                    setParallaxPosition($doc, multiplier, $object);
                });
            }
        };

        var background_image_parallax_2 = function ($object, multiplier) {
            multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
            multiplier = 1 - multiplier;
            var $doc = $(document);
            $object.css({ "background-attachment": "fixed" });
            $(window).scroll(function () {
                var firstTop = $object.offset().top,
                    pos = $(window).scrollTop(),
                    yPos = Math.round((multiplier * (firstTop - pos)) - 186);

                var bg_css = 'center ' + yPos + 'px';

                $object.css({ "background-position": bg_css });
            });
        };

        $(function () {
            // Hero Section - Background Parallax
            background_image_parallax($(".tm-parallax"), 0.30, false);
            background_image_parallax_2($("#contact"), 0.80);

            // Handle window resize
            window.addEventListener('resize', function () {
                background_image_parallax($(".tm-parallax"), 0.30, true);
            }, true);

            // Detect window scroll and update navbar
            $(window).scroll(function (e) {
                if ($(document).scrollTop() > 120) {
                    $('.tm-navbar').addClass("scroll");
                } else {
                    $('.tm-navbar').removeClass("scroll");
                }
            });

            // Close mobile menu after click 
            $('#tmNav a').on('click', function () {
                $('.navbar-collapse').removeClass('show');
            })

            // Scroll to corresponding section with animation
            $('#tmNav').singlePageNav();

            // Add smooth scrolling to all links
            // https://www.w3schools.com/howto/howto_css_smooth_scroll.asp
            $("a").on('click', function (event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;

                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 400, function () {
                        window.location.hash = hash;
                    });
                } // End if
            });

            // Pop up
            $('.tm-gallery').magnificPopup({
                delegate: 'a',
                type: 'image',
                gallery: { enabled: true }
            });

            // Gallery
            $('.tm-gallery').slick({
                dots: true,
                infinite: false,
                slidesToShow: 5,
                slidesToScroll: 2,
                responsive: [
                    {
                        breakpoint: 1199,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 991,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 767,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    </script>
</body>

</html>

templates/steg/encode.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Encoder</title>
<link rel="stylesheet" href="{{ STATIC_URL }}style.css" />
</head>



<body>
    <div>
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}
            {% comment %}
            <a href="{% url 'steg:show_image' %}"><input type="submit" value="Upload" /></a>
            {% endcomment %}
            <input type="submit" value="Upload" />
        </form>

        
        {% comment %}
        <h2>Which algorithm do you want to use?</h2>
        <a href="{% url 'steg:lsbEncode' %}">
            <input type="button" value="LSB" id="lsb_enc_button" name="lsb_enc_button">
        </a>
        
        <br>
        <br>
        
        <a href="{% url 'steg:mnfEncode' %}">
            <input type="button" value="MnF" id="mnf_enc_button" name="mnf_enc_button">
        </a>
        {% endcomment %}

    </div>
</body>

</html>

templates/steg/lsbEncoder.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>LSB Encoder</title>
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'steg/all.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/slick.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/slick-theme.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/magnific-popup.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/bootstrap.min.css' %}">
    <link rel="stylesheet" type="text/css" href="{% static 'steg/templatemo-style.css' %}">
</head>



<body style="background-color: rgb(210, 204, 187);  color: #000;">
    <section>
        <nav class="navbar navbar-expand-md tm-navbar" id="tmNav"
            style=" background-color: rgb(216, 161, 132);color: #000; margin-top: -10%;">
            <div class="container">
                <div class="tm-next">
                    <a href="{% url 'steg:index' %}" class="navbar-brand" style="color: #000;" title="Go to Home Page!">SETGANO</a>
                </div>

                <button class="navbar-toggler" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation">
                    <i class="fas fa-bars navbar-toggler-icon"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarSupportedContent">
                    <ul class="navbar-nav ml-auto">
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="{% url 'steg:encode' %}"
                                style="color: #000;">ENCODE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="{% url 'steg:decode' %}"
                                style="color: #000;">DECODE</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link tm-nav-link" href="#contact" style="color: #000;">CONTACT US</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </section>
    <div style="margin: 10%; z-index: -1;">
        <h1>Welcome to LSB Encoder!</h1><br><br>
        <h2>Upload any image of your choice and enter the message you want to hide!</h2><br>
        <form enctype="multipart/form-data" method="POST" action="">
            {% csrf_token %}
            {{ form.as_p }}

            <input type="submit" class="button-56 tm-btn-primary" value="Upload" />
        </form>



    </div>

    <br>
    <section id="contact" style="margin: -5%; margin-top: 0;" class="tm-section-pad-top tm-parallax-2">
        <div class="container tm-container-contact">
            <div class="row">
                <div class="col-12">
                    <h2 class="mb-4 tm-section-title">Contact Us</h2>
                    <div class="mb-5 tm-underline">
                        <div class="tm-underline-inner"></div>
                    </div>
                    <p class="mb-5">
                        This is a project done by Poorna Hegde, Saniya Bhargava and Sonali R under Nirmal V Nair and
                        Ganesh
                        S for ACM NITK.
                    </p>
                </div>

                <div class="col-sm-12 col-md-6 d-flex align-items-center tm-contact-item">
                    <a href="tel:0100200340" class="tm-contact-item-link">
                        <!-- <i class="fas fa-3x fa-phone mr-4"></i> -->
                        <span class="mb-0">0100200340</span>
                    </a>
                </div>
                <div class="col-sm-12 col-md-6 d-flex align-items-center tm-contact-item">
                    <a href="mailto:acm@nitk.edu.in" class="tm-contact-item-link">
                        <!-- <i class="fas fa-3x fa-envelope mr-4"></i> -->
                        <span class="mb-0">acm@nitk.edu.in</span>
                    </a>
                </div>
            </div>
        </div>
        <footer class="text-center small tm-footer">
            <p class="mb-0">
                Copyright &copy; 2022 ACM

                - Design: <a rel="nofollow" href="https://templatemo.com" class="tm-footer-link">Template Mo</a>
            </p>
        </footer>
    </section>
    <script src="js/jquery-1.9.1.min.js"></script>
    <script src="slick/slick.min.js"></script>
    <script src="magnific-popup/jquery.magnific-popup.min.js"></script>
    <script src="js/jquery.singlePageNav.min.js"></script>
    <script src="js/bootstrap.min.js"></script>
    <script>

        function getOffSet() {
            var _offset = 450;
            var windowHeight = window.innerHeight;

            if (windowHeight > 500) {
                _offset = 400;
            }
            if (windowHeight > 680) {
                _offset = 300
            }
            if (windowHeight > 830) {
                _offset = 210;
            }

            return _offset;
        }

        function setParallaxPosition($doc, multiplier, $object) {
            var offset = getOffSet();
            var from_top = $doc.scrollTop(),
                bg_css = 'center ' + (multiplier * from_top - offset) + 'px';
            $object.css({ "background-position": bg_css });
        }

        // Parallax function
        // Adapted based on https://codepen.io/roborich/pen/wpAsm        
        var background_image_parallax = function ($object, multiplier, forceSet) {
            multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
            multiplier = 1 - multiplier;
            var $doc = $(document);
            // $object.css({"background-attatchment" : "fixed"});

            if (forceSet) {
                setParallaxPosition($doc, multiplier, $object);
            } else {
                $(window).scroll(function () {
                    setParallaxPosition($doc, multiplier, $object);
                });
            }
        };

        var background_image_parallax_2 = function ($object, multiplier) {
            multiplier = typeof multiplier !== 'undefined' ? multiplier : 0.5;
            multiplier = 1 - multiplier;
            var $doc = $(document);
            $object.css({ "background-attachment": "fixed" });
            $(window).scroll(function () {
                var firstTop = $object.offset().top,
                    pos = $(window).scrollTop(),
                    yPos = Math.round((multiplier * (firstTop - pos)) - 186);

                var bg_css = 'center ' + yPos + 'px';

                $object.css({ "background-position": bg_css });
            });
        };

        $(function () {
            // Hero Section - Background Parallax
            background_image_parallax($(".tm-parallax"), 0.30, false);
            background_image_parallax_2($("#contact"), 0.80);

            // Handle window resize
            window.addEventListener('resize', function () {
                background_image_parallax($(".tm-parallax"), 0.30, true);
            }, true);

            // Detect window scroll and update navbar
            $(window).scroll(function (e) {
                if ($(document).scrollTop() > 120) {
                    $('.tm-navbar').addClass("scroll");
                } else {
                    $('.tm-navbar').removeClass("scroll");
                }
            });

            // Close mobile menu after click 
            $('#tmNav a').on('click', function () {
                $('.navbar-collapse').removeClass('show');
            })

            // Scroll to corresponding section with animation
            $('#tmNav').singlePageNav();

            // Add smooth scrolling to all links
            // https://www.w3schools.com/howto/howto_css_smooth_scroll.asp
            $("a").on('click', function (event) {
                if (this.hash !== "") {
                    event.preventDefault();
                    var hash = this.hash;

                    $('html, body').animate({
                        scrollTop: $(hash).offset().top
                    }, 400, function () {
                        window.location.hash = hash;
                    });
                } // End if
            });

            // Pop up
            $('.tm-gallery').magnificPopup({
                delegate: 'a',
                type: 'image',
                gallery: { enabled: true }
            });

            // Gallery
            $('.tm-gallery').slick({
                dots: true,
                infinite: false,
                slidesToShow: 5,
                slidesToScroll: 2,
                responsive: [
                    {
                        breakpoint: 1199,
                        settings: {
                            slidesToShow: 4,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 991,
                        settings: {
                            slidesToShow: 3,
                            slidesToScroll: 2
                        }
                    },
                    {
                        breakpoint: 767,
                        settings: {
                            slidesToShow: 2,
                            slidesToScroll: 1
                        }
                    },
                    {
                        breakpoint: 480,
                        settings: {
                            slidesToShow: 1,
                            slidesToScroll: 1
                        }
                    }
                ]
            });
        });
    </script>
</body>

</html>